# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 305fbb31a016af2b29d3b27c586971fe52d63930b383c28b23d7bb98ed1576e68a967f0dfd57f62c018cd836b5223399d59ab979abaf5c80fff0c924e7bf57c9

test:
  secret_key_base: 08ddf7ea936578ff07be829eb54ce669422cc03af774c3e4ae9777279c652f3876407a3bacb30e53d998c220076444d3097ddf241f9134aa39de8bb4c1d705c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
